#!/bin/bash

# sudo apt-get install wmctrl xdotool

SWITCH_DIR="/tmp/showwin/$1"
mkdir -p "$SWITCH_DIR"

MATCHED=`wmctrl -l -x | grep -i "$1"`
CURRENT=`xdotool getwindowfocus getwindowname`
MATCHED_CURRENT=`echo "$MATCHED" | grep -F "$CURRENT" | head -1 | cut -d" " -f1`

PINNED=`ls "$SWITCH_DIR"`
MATCHED_PINNED=`echo "$MATCHED" | grep "^$PINNED"`

if [[ -n $MATCHED_PINNED ]]; then
  MATCHED=$MATCHED_PINNED
fi

if [[ -n $MATCHED_CURRENT ]]; then
  echo Setting new current window $MATCHED_CURRENT
  rm -r "$SWITCH_DIR"/* > /dev/null
  mkdir -p "$SWITCH_DIR/$MATCHED_CURRENT"
elif [[ -n $MATCHED ]]; then
  WINID=`echo "$MATCHED" | head -1 | cut -d" " -f1`
  echo Switching to window $WINID
  wmctrl -a $WINID -i
else
  echo Opening new window $2&
  $2&
fi
